### ISSUE TITLE
TypeError: drop() got an unexpected keyword argument 'columns'

### ISSUE THREAD

**Issue by ghost** [hatalis/Quantile_Detector#1]
Hello,
  I tried your code and got this error:

python main.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    experiment = split_data(experiment, scaling=MinMaxScaler(), test_size=2/30) # StandardScaler()
  File "C:\Work\code\processing\split_data.py", line 23, in split_data
    X = Xy.drop(columns=['Load'])
TypeError: drop() got an unexpected keyword argument 'columns'

      Thanks for your help!

**Comment by hatalis** [comment]
'Load' was part of a data set on power systems, when using your own data for detection you will need to alter the code (eg name of the columns) with domain specifics of your data. Hope that helps!

**Comment by ghost** [comment]
I used your code and your data, and did not change anything.   Could you try it by yourself?
  Thanks!

**Comment by Tommylushixiang** [comment]
Thank you for your contribution，
I tried your code and got this error:

python detector.py  line 52, in 
model.compile(loss=lambda Y, Q: pinball_loss(tau, Y, Q, alpha, smooth_loss, kappa, margin), optimizer=optimizer)
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`)
